{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $svc.account }}
  labels:
    {{- include "book-info.labels" $ | nindent 4 }}
    account: {{ $name }}
---
{{- end }}
