apiVersion: v2
name: redis
description: A Helm chart that deploys Redis

type: application
version: 0.1.0

dependencies:
  - name: redis
    version: 0.33.0
    repository: oci://registry-1.docker.io/cloudpirates
